import type { DiffFile, Finding, Provider, PullRequestInfo, ReviewResult } from "./types.js";
import { renderFiles } from "./prompt.js";
import { validateFindings } from "./diff.js";

export interface ReviewOptions {
  locale: string;
  /** Glob-free substring excludes, e.g. ["package-lock.json", "dist/"]. */
  exclude: string[];
  /** Character budget for the diff portion of one model request. */
  batchCharBudget: number;
  log: (message: string) => void;
}

export const DEFAULT_EXCLUDES = [
  "package-lock.json",
  "yarn.lock",
  "pnpm-lock.yaml",
  ".min.js",
  ".map",
  "dist/",
  "build/",
  "vendor/",
];

export function filterFiles(files: DiffFile[], exclude: string[]): DiffFile[] {
  return files.filter((f) => !exclude.some((pattern) => f.path.includes(pattern)));
}

/** Split files into batches whose annotated patches fit the character budget. */
export function batchFiles(files: DiffFile[], budget: number): DiffFile[][] {
  const batches: DiffFile[][] = [];
  let current: DiffFile[] = [];
  let size = 0;
  for (const file of files) {
    if (current.length > 0 && size + file.patch.length > budget) {
      batches.push(current);
      current = [];
      size = 0;
    }
    current.push(file);
    size += file.patch.length;
  }
  if (current.length > 0) batches.push(current);
  return batches;
}

export async function runReview(
  provider: Provider,
  pr: PullRequestInfo,
  options: ReviewOptions,
): Promise<{ result: ReviewResult; dropped: Finding[] }> {
  const files = filterFiles(pr.files, options.exclude);
  if (files.length === 0) {
    return {
      result: { summary: "No reviewable files in this pull request.", findings: [] },
      dropped: [],
    };
  }

  const batches = batchFiles(files, options.batchCharBudget);
  options.log(
    `Reviewing ${files.length} file(s) in ${batches.length} batch(es) with ${provider.name}:${provider.model}`,
  );

  const summaries: string[] = [];
  const findings: Finding[] = [];
  for (const [i, batch] of batches.entries()) {
    if (batches.length > 1) options.log(`Batch ${i + 1}/${batches.length}: ${batch.length} file(s)`);
    const result = await provider.review({
      prTitle: pr.title,
      prBody: pr.body,
      filesText: renderFiles(batch),
      locale: options.locale,
    });
    summaries.push(result.summary);
    findings.push(...result.findings);
  }

  const { valid, dropped } = validateFindings(findings, files);
  if (dropped.length > 0) {
    options.log(`Dropped ${dropped.length} finding(s) referencing lines outside the diff.`);
  }

  return {
    result: { summary: buildSummary(summaries, valid, provider), findings: valid },
    dropped,
  };
}

function buildSummary(summaries: string[], findings: Finding[], provider: Provider): string {
  const counts = new Map<string, number>();
  for (const f of findings) counts.set(f.severity, (counts.get(f.severity) ?? 0) + 1);
  const countLine =
    findings.length === 0
      ? "No issues found."
      : ["critical", "warning", "suggestion", "nitpick"]
          .filter((s) => counts.has(s))
          .map((s) => `${counts.get(s)} ${s}`)
          .join(" · ");

  return [
    "## 🔎 pr-sage review",
    "",
    summaries.join("\n\n"),
    "",
    `**Findings:** ${countLine}`,
    "",
    `<sub>Generated by [pr-sage](https://www.npmjs.com/package/pr-sage) using ${provider.name}:${provider.model}</sub>`,
  ].join("\n");
}
